# Generated by Django 3.2.20 on 2024-01-31 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateField(verbose_name=datetime.datetime(2024, 1, 31, 9, 34, 6, 594847, tzinfo=utc))),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
