# Generated by Django 3.2.20 on 2024-01-31 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2024, 1, 31, 9, 38, 15, 130212, tzinfo=utc)),
        ),
    ]
